matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required  
  - os: osx
    osx_image: xcode8.2
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;      
    sudo apt-get install liblapack3 liblapacke liblapacke-dev -y;
    sudo apt-get install libopenblas-base libopenblas-dev -y;
    git clone https://github.com/IBM-Swift/Package-Builder.git;
  fi
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    xcodebuild test -scheme Nifty;
  fi   
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    bash <(curl -s https://codecov.io/bash);
  fi     